spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budgetdb
    username: brightvl
    password: brightPass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# JWT Configuration
test:
  app:
    secret: "мой-длинный-ключ-для-HS256"
    lifetime: 3600000  # Время жизни токена в миллисекундах (например, 1 час)

#  docker run --name budgetdb -e POSTGRES_USER=brightvl -e POSTGRES_PASSWORD=brightPass -e POSTGRES_DB=budgetdb -p 5432:5432 -d postgres
#  --name budget-postgres — задает имя контейнера.
#  -e POSTGRES_PASSWORD=yourPassword — устанавливает пароль для пользователя PostgreSQL.
#  -e POSTGRES_USER=yourUsername — устанавливает имя пользователя.
#  -e POSTGRES_DB=budgetdb — создает базу данных с именем budgetdb.
#  -p 5432:5432 — маппинг порта 5432 контейнера на порт 5432 хоста.
#  -d postgres — запускает контейнер в фоновом режиме с последней версией PostgreSQL.