version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: habitdb
      POSTGRES_USER: brightvl
      POSTGRES_PASSWORD: habitpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rest-service:
    build:
      context: ./rest
      dockerfile: Dockerfile
    container_name: rest-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/habitdb
      SPRING_DATASOURCE_USERNAME: brightvl
      SPRING_DATASOURCE_PASSWORD: habitpass
    depends_on:
      - postgres-db

  thymeleaf-service:
    build:
      context: ./thymeleaf
      dockerfile: Dockerfile
    container_name: thymeleaf-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/habitdb
      SPRING_DATASOURCE_USERNAME: brightvl
      SPRING_DATASOURCE_PASSWORD: habitpass
    depends_on:
      - postgres-db

volumes:
  postgres_data:
