app:
  jwt:
    secret: "мой-длинный-ключ-для-HS256"
    lifetime: 3600000
  db:
    name: appdb
    user: appUser
    password: appPass
    host: localhost
    port: 5432

spring:
  datasource:
    url: jdbc:postgresql://${app.db.host}:${app.db.port}/${app.db.name}
    username: ${app.db.user}
    password: ${app.db.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080